### PR TITLE
Project changes for testing new ng2-completer version

### PR DESCRIPTION
**Pull request by oferh**

### CODE REVIEW

**Comment by kodeine** [comment]
@oferh thanks for working hard on this, quick question, ionic and angular moved to version 2.2.1
but it seems you changed from 2.1.1 to 2.0.0?


```
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
```

**Comment by oferh** [comment]
I've encountered this issue: https://forum.ionicframework.com/t/ionic-build-module-has-no-exported-member-wrapper-toolbaritem/68439
So I had to downgrade, you can check again if there's a new version

**Comment by kodeine** [comment]
@oferh 
so i've installed it and tried to run, it compiles just fine now, but `ionic serve` (non-aot) gives errors probably because its already compiled as AOT and `ionic serve` wants it non-aot?

So when using ngc/aot compile, everything compiles fine but when i run the application i see the following error. 

screenshot from 2016-11-21 10-55-41


To *test* this, open `package.json` and replace this
```
    "serve:before": "watch",
```
to 
```
    "serve:before": "build",  // changed it to use aot
```

And then run `ionic serve` it will build using ngc and open the browser, you can easily debug then.

**Comment by oferh** [comment]
@kodeine there are 2 bugs that are blocking it at the moment:
https://github.com/driftyco/ionic/pull/9211 which is already resolved in the latest angular release and https://github.com/driftyco/ionic/pull/9211 which will be resolved in the next ionic release.
we need to tests again when it is released.

**Comment by kodeine** [comment]
@oferh we can update the `ionic-angular` in package.json to @nightly.

so maybe we can test now using, `npm install ionic-angular@nightly`

**Comment by kodeine** [comment]
@oferh 
works like a charm after updating package.js, wohoo! thanks a bunch. 

Is there a way to keep it working for non-aot as well? otherwise i would have to remove aot compiled and replace it with regular everytime i will be testing non-aot.

**Comment by oferh** [comment]
it works for non AOT as well, I'll make some more tests and release a new version for ng2-completer

**Comment by kodeine** [comment]
@oferh if i run with ionic serve (non aot) i get this error in console.

```
[21:20:54]  build dev failed: Cannot read property 'indexOf' of undefined 
```

**Comment by oferh** [comment]
@kodeine, I've tried again and all working for me, if you reinstall all `node_modules`do you still get the error?

**Comment by kodeine** [comment]
@oferh i deleted the node_modules and tried like 10 times lol same thing. the fix is to goto each metadata.json file and change the version to 1 from 2.

**Comment by oferh** [comment]
are you using ionic `2.1.0`?

**Comment by kodeine** [comment]
```
    "@angular/common": "2.2.3",
    "@angular/compiler": "2.2.3",
    "@angular/compiler-cli": "2.2.3",
    "@angular/core": "2.2.3",
    "@angular/forms": "2.2.3",
    "@angular/http": "2.2.3",
    "@angular/platform-browser": "2.2.3",
    "@angular/platform-browser-dynamic": "2.2.3",
    "@angular/platform-server": "2.2.3",
```

**Comment by oferh** [comment]
The output of `ionic --version`

**Comment by kodeine** [comment]
```
$ ionic --version
2.1.13


$ ionic info

Your system information:

Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.3-201611302233
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.2
Node Version: v6.6.0
Xcode version: Not installed

```

**Comment by oferh** [comment]
just upgraded ionic to `2.1.14` all seems to work fine.
this is `ngc` issue that was supposed to be resolved in `2.2.3` https://github.com/angular/angular/issues/13057 
checkout if you have `ngc` installed globally

**Comment by kodeine** [comment]
How can i check if ngc is globally installed?

**Comment by oferh** [comment]
check [here](http://stackoverflow.com/questions/26104276/how-to-tell-if-npm-package-was-installed-globally-or-locally)

**Comment by kodeine** [comment]
@oferh `npm list -g | grep ngc` shows blank. so its not globally installed.

**Comment by kodeine** [comment]
@oferh 
i'm trying to install completer other than ionic, its an [angular-starter](https://github.com/qdouble/angular-webpack2-starter), same issue, i had to update the meta version manually but it might be because starter is still on older version of angular. But i see another error while compiling for AOT.


```
ERROR in ./src/compiled/src/app/components/auto-completer/completer-cmp-md.ngfactory.ts
Module not found: Error: Can't resolve '../../../../node_modules/ng2-completer/components/ng2-completer/completer-list-item-cmp.ngfactory' in '/Projects/SL/another/src/compiled/src/app/components/auto-completer'
 @ ./src/compiled/src/app/components/auto-completer/completer-cmp-md.ngfactory.ts 37:15-123
 @ ./src/compiled/src/app/features/signup/signup.page.ngfactory.ts
 @ ./src/compiled/src/app/app.module.ngfactory.ts
 @ ./src/main.browser.aot.ts

ERROR in [default] /Projects/SL/another/src/compiled/src/app/components/auto-completer/completer-cmp-md.ngfactory.ts:39:26 
Cannot find module '../../../../node_modules/ng2-completer/components/ng2-completer/completer-list-item-cmp.ngfactory'.
```

Since i'm using material design.
`/Projects/SL/another/src/app/components/auto-completer.ts`

```ts
// "use strict";
import { Component, Input, Output, EventEmitter, OnInit, ViewChild, forwardRef } from "@angular/core";
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from "@angular/forms";

import { CtrCompleter, CompleterData, CompleterItem } from "ng2-completer";
// import { MAX_CHARS, MIN_SEARCH_LENGTH, PAUSE, TEXT_SEARCHING, TEXT_NORESULTS } from "ng2-completer/globals";


import "rxjs/add/operator/catch";

export const MAX_CHARS = 524288;  // the default max length per the html maxlength attribute
export const MIN_SEARCH_LENGTH = 3;
export const PAUSE = 250;
export const TEXT_SEARCHING = "Searching...";
export const TEXT_NORESULTS = "No results found";

const noop = () => { };

const COMPLETER_CONTROL_VALUE_ACCESSOR = {
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => CompleterCmpMd),
    multi: true
};


@Component({
    selector: "ng2-completer-md",
    templateUrl: "./completer-cmp-md.html",
    styleUrls: ["./completer-cmp-md.css"],
    providers: [COMPLETER_CONTROL_VALUE_ACCESSOR]
})
export class CompleterCmpMd implements OnInit, ControlValueAccessor {
    @Input() public dataService: CompleterData;
    @Input() public inputName = "";
    @Input() public pause = PAUSE;
    @Input() public minSearchLength = MIN_SEARCH_LENGTH;
    @Input() public maxChars = MAX_CHARS;
    @Input() public overrideSuggested = false;
    @Input() public clearSelected = false;
    @Input() public placeholder = "";
    @Input() public matchClass: string;
    @Input() public textSearching = TEXT_SEARCHING;
    @Input() public textNoResults = TEXT_NORESULTS;
    @Input() public fieldTabindex: number;
    @Input() public autoMatch = false;
    @Input() public disableInput = false;
    @Output() public selected = new EventEmitter<CompleterItem>();
    @Output() public highlighted = new EventEmitter<CompleterItem>();
    @Output() public blur = new EventEmitter<void>();

    @ViewChild(CtrCompleter) public completer: CtrCompleter;

    private displaySearching = true;
    public searchStr = "";
    private _onTouchedCallback: () => void = noop;
    private _onChangeCallback: (_: any) => void = noop;

    constructor() { }

    get value(): any { return this.searchStr; };

    set value(v: any) {
        if (v !== this.searchStr) {
            this.searchStr = v;
            this._onChangeCallback(v);
        }
    }

    public onTouched() {
        this._onTouchedCallback();
    }

    public writeValue(value: any) {
        this.searchStr = value;
    }

    public registerOnChange(fn: any) {
        this._onChangeCallback = fn;
    }

    public registerOnTouched(fn: any) {
        this._onTouchedCallback = fn;
    }

    public ngOnInit() {
        this.completer.selected.subscribe((item: CompleterItem) => {
             let title = item ? item.title : "";
             this.selected.emit(item);
             this._onChangeCallback(title);
        });
        this.completer.highlighted.subscribe((item: CompleterItem) => {
             this.highlighted.emit(item);
        });

        if (this.textSearching === "false") {
            this.displaySearching = false;
        }
    }

    public onBlur() {
        this.blur.emit();
        this.onTouched();
    }
}
```

**Comment by kodeine** [comment]
@oferh 
btw i'm getting these warnings too when i compile,

```

WARNING in ./~/ng2-completer/directives/ctr-input.js
Cannot find source file '../../../../src/directives/ctr-input.ts': Error: Can't resolve '../../../../src/directives/ctr-input.ts' in '/Projects/SL/another/node_modules/ng2-completer/directives'
 @ ./src/compiled/src/app/components/auto-completer/completer-cmp-md.ngfactory.ts 22:15-60
 @ ./src/compiled/src/app/features/signup/signup.page.ngfactory.ts
 @ ./src/compiled/src/app/app.module.ngfactory.ts
 @ ./src/main.browser.aot.ts

WARNING in ./~/ng2-completer/components/ng2-completer/services/completer-base-data.js
Cannot find source file '../../../../../../src/components/ng2-completer/services/completer-base-data.ts': Error: Can't resolve '../../../../../../src/components/ng2-completer/services/completer-base-data.ts' in '/Projects/SL/another/node_modules/ng2-completer/components/ng2-completer/services'
 @ ./~/ng2-completer/components/ng2-completer/services/local-data.js 8:0-58
 @ ./src/compiled/src/app/app.module.ngfactory.ts
 @ ./src/main.browser.aot.ts

WARNING in ./~/ng2-completer/components/ng2-completer/completer-cmp.js
Cannot find source file '../../../../../src/components/ng2-completer/completer-cmp.ts': Error: Can't resolve '../../../../../src/components/ng2-completer/completer-cmp.ts' in '/Projects/SL/another/node_modules/ng2-completer/components/ng2-completer'
 @ ./~/ng2-completer/ng2-completer.module.js 4:0-72
 @ ./src/compiled/src/app/app.module.ngfactory.ts
 @ ./src/main.browser.aot.ts

WARNING in ./~/ng2-completer/globals.js
Cannot find source file '../../../src/globals.ts': Error: Can't resolve '../../../src/globals.ts' in '/Projects/SL/another/node_modules/ng2-completer'
 @ ./~/ng2-completer/directives/ctr-list.js 4:0-54
 @ ./src/compiled/src/app/components/auto-completer/completer-cmp-md.ngfactory.ts
 @ ./src/compiled/src/app/features/signup/signup.page.ngfactory.ts
 @ ./src/compiled/src/app/app.module.ngfactory.ts
 @ ./src/main.browser.aot.ts

```

**Comment by kodeine** [comment]
@oferh can you help?

**Comment by kodeine** [comment]
@oferh you're available? :)

seems like package is not able to compile outside of ionic? i tried to do the same steps in [readme](https://github.com/kodeine/completer-test/blob/master/README.md) and it doesnt work anymore. i even tried the master branch and then tried building same error. Its outside of ionic environment though.

**Comment by oferh** [comment]
Hi @kodeine I'm still here :-)
let's connect in [gitter]( https://gitter.im/ng2-completer)

**Pull request merged**
